# Generated by Django 6.0.3 on 2026-03-16 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vote_cast', 'Vote Cast'), ('voter_verified', 'Voter Verified'), ('voter_imported', 'Voter Imported'), ('aspirant_added', 'Aspirant Added'), ('token_generated', 'Tokens Generated'), ('token_sms_sent', 'Token SMS Sent'), ('token_sms_failed', 'Token SMS Failed'), ('bad_token', 'Wrong Token Submitted'), ('token_reuse', 'Token Reuse Attempt'), ('no_token_issued', 'Voter Has No Token Issued'), ('fp_mismatch', 'Fingerprint Mismatch at Vote Time'), ('fp_duplicate', 'Fingerprint Duplicate — possible multi-vote'), ('rate_limit_hit', 'Rate Limit Hit'), ('invalid_session_token', 'Invalid Session Vote Token'), ('election_closed', 'Vote Attempted While Election Closed')], max_length=50)),
                ('actor', models.CharField(help_text='Student ID or admin username', max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, help_text='When voting opens. Leave blank to open immediately.', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When voting closes. Leave blank for no automatic close.', null=True)),
                ('results_visible', models.BooleanField(default=False, help_text='Make the results page publicly visible.')),
            ],
            options={
                'verbose_name': 'Election settings',
                'verbose_name_plural': 'Election settings',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voter_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aspirant_images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspirants', to='election.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(help_text='e.g. PHA/0003/20', max_length=50, unique=True, verbose_name='Student ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Used as the second verification factor at login.', max_length=254, verbose_name='Email address')),
                ('sms_token_hash', models.CharField(blank=True, editable=False, help_text='SHA-256 of the 6-char SMS token. Plaintext never stored.', max_length=64, verbose_name='Token Hash')),
                ('token_issued', models.BooleanField(default=False, editable=False, verbose_name='Token Issued')),
                ('token_verified', models.BooleanField(default=False, editable=False, verbose_name='Token Verified')),
                ('sms_sent', models.BooleanField(default=False, editable=False, verbose_name='SMS Sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sms_failed_reason', models.CharField(blank=True, editable=False, max_length=255)),
                ('vote_session_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('has_voted', models.BooleanField(default=False, editable=False)),
                ('voted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('voted_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.classgroup')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_hash', models.CharField(blank=True, max_length=64)),
                ('webgl_vendor', models.CharField(blank=True, max_length=128)),
                ('webgl_renderer', models.CharField(blank=True, max_length=128)),
                ('screen_info', models.CharField(blank=True, max_length=64)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('composite_hash', models.CharField(db_index=True, max_length=64)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprint', to='election.voter')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.aspirant')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.portfolio')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.voter')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voter', 'aspirant'), name='unique_voter_aspirant'), models.UniqueConstraint(fields=('voter', 'portfolio'), name='unique_voter_portfolio')],
            },
        ),
    ]
