# Generated by Django 5.1.4 on 2025-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="image",
        ),
        migrations.AlterField(
            model_name="voter",
            name="has_voted",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
